### ISSUE TITLE
Cannot work with compressed pcd

### ISSUE THREAD

**Issue by boyang9602** [MapIV/pypcd4#22]
Hi there,

Thank you for the great work! I met the error below, do you have any idea of this error? Thank you!

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bo/miniconda3/envs/pytorch/lib/python3.8/site-packages/pypcd4/pypcd4.py", line 261, in from_path
    return PointCloud.from_fileobj(fp)
  File "/home/bo/miniconda3/envs/pytorch/lib/python3.8/site-packages/pypcd4/pypcd4.py", line 233, in from_fileobj
    pc_data = _parse_pc_data(fp, metadata)
  File "/home/bo/miniconda3/envs/pytorch/lib/python3.8/site-packages/pypcd4/pypcd4.py", line 187, in _parse_pc_data
    buffer = lzf.decompress(fp.read(compressed_size), uncompressed_size)
AttributeError: module 'lzf' has no attribute 'decompress'
```

**Comment by boyang9602** [comment]
Seems like a python version issue, not sure. I used python 3.8 in conda

**Comment by boyang9602** [comment]
I think I can confirm that it is a python version issue. I created one clean python 3.8 env and one clean python 3.11 in conda.

Python 3.8
```
(tmp2) ✔ ~/projects/LocNDF [main|…3] 
18:45 $ python
Python 3.8.19 (default, Mar 20 2024, 19:58:24) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pypcd4 import PointCloud
>>> pcd = PointCloud.from_path("ColumbiaPark/2018-10-11/pcds/1000.pcd")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bo/miniconda3/envs/tmp2/lib/python3.8/site-packages/pypcd4/pypcd4.py", line 261, in from_path
    return PointCloud.from_fileobj(fp)
  File "/home/bo/miniconda3/envs/tmp2/lib/python3.8/site-packages/pypcd4/pypcd4.py", line 233, in from_fileobj
    pc_data = _parse_pc_data(fp, metadata)
  File "/home/bo/miniconda3/envs/tmp2/lib/python3.8/site-packages/pypcd4/pypcd4.py", line 187, in _parse_pc_data
    buffer = lzf.decompress(fp.read(compressed_size), uncompressed_size)
AttributeError: module 'lzf' has no attribute 'decompress'
>>> 
```

Python 3.11
```
18:42 $ python
Python 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pypcd4 import PointCloud
>>> pcd = PointCloud.from_path("ColumbiaPark/2018-10-11/pcds/1000.pcd")
>>> pcd.numpy()
array([[-1.99902172e+01, -3.02818966e+00, -2.31144094e+00,
         1.43000000e+02,  1.22324355e+09],
       [-2.14173756e+01, -3.97245312e+00, -2.38133454e+00,
         1.51000000e+02,  1.22324355e+09],
       [-4.40083427e+01, -1.29852591e+01,  2.70792931e-01,
         2.16000000e+02,  1.22324355e+09],
       ...,
       [-1.48014488e+01, -4.26814842e+00, -2.21298957e+00,
         9.00000000e+01,  1.22324355e+09],
       [-1.00869751e+01, -2.12456894e+00, -2.10196733e+00,
         8.10000000e+01,  1.22324355e+09],
       [-1.05974884e+01, -2.81252408e+00, -2.12533903e+00,
         9.70000000e+01,  1.22324355e+09]])
>>> 
```

Maybe the root issue is from python-lzf?

**Comment by boyang9602** [comment]
It is more of an issue of conda. python-lzf does not work well for conda python 3.8. However, it works well for native Ubuntu python 3.8.

**Comment by boyang9602** [comment]
An update: I finally realized that [`lzf`](https://github.com/lordmauve/lzf) is installed instead of [`python-lzf`](https://github.com/teepark/python-lzf).
