### ISSUE TITLE
'intensity' cannot be extracted using pc.numpy(('intensity'))

### ISSUE THREAD

**Issue by tokuda99** [MapIV/pypcd4#3]
When I run the following code, it displays as follows.
```
from pypcd4 import PointCloud
import numpy as np
data = np.load("test.npy")
pc = PointCloud.from_xyzi_points(data)
print(pc.fields)
intensity = pc.numpy(('intensity'))
print(intensity)
```

```
('x', 'y', 'z', 'intensity')
Traceback (most recent call last):
  File "tester.py", line 9, in <module>
    intensity = pc.numpy(('intensity'))
  File "/usr/local/lib/python3.8/dist-packages/pypcd4/pypcd4.py", line 681, in numpy
    _stack = tuple(self.pc_data[field] for field in fields)
  File "/usr/local/lib/python3.8/dist-packages/pypcd4/pypcd4.py", line 681, in <genexpr>
    _stack = tuple(self.pc_data[field] for field in fields)
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/records.py", line 509, in __getitem__
    obj = super().__getitem__(indx)
ValueError: no field of name i
```
When retrieving a field, it is possible that only the first character is retrieved.

**Comment by urasakikeisuke** [comment]
The ('intensity') object is equivalent to 'intensity' in Python and is treated as a string. Instead, pass it as ('intensity',) or ['intensity'].
````python
print(type(('intensity')))
# <class 'str'>

print(type(('intensity', ))))
# <class 'tuple'>
```
